version: '3'
services:
  sql-server-db:
    container_name: sql-server-db
    image: mcr.microsoft.com/mssql/server:2019-latest
    restart: always
    environment:
      SA_PASSWORD: "DevopsLogin512"
      ACCEPT_EULA: "Y"
      MSSQL_PID: "Developer"
    ports:
      - "1433:1433"
    volumes:
      - mssql-db:/var/opt/mssql
# Names our volume
volumes:
  mssql-db:
