version: '3'
services:
  mysql_db_container:
    image: mysql:latest
    #command: --default-authentication-plugin=mysql_native_password
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_DATABASE: 'testingdb'
      # So you don't have to use root, but you can if you like
      MYSQL_USER: 'mysqluser'
      # You can use whatever password you like
      MYSQL_PASSWORD: 'password'
      
    ports:
      - 3306:3306
    volumes:
      - mysql_db_data_container:/var/lib/mysql
  adminer_container:
    image: adminer:latest
    environment:
      ADMINER_DEFAULT_SERVER: mysql_db_container
    ports:
      - 8080:8080

volumes:
  mysql_db_data_container: